#Durid数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.138.215:3306/studentSystem?characterEncoding=utf-8&useSSL=false
    username: root
    password: yingkun9257
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:/sqlmap/*
  config-location: classpath:/mybatis-config.xml
pagehelper:
  reasonable: true #分页参数合理化
  helper-dialect: mysql  #方言
  support-methods-arguments: true
  params: count=countSql
